name: ciao
run-name: ciao da parte di ${{ github.actor }} 
on: [push]
jobs:
  ciao-fa-cose:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ciaooooooooooooooooooooo"
      - name: Set up JDK for x64
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.3'
          distribution: 'temurin'
      - run: mvn -v
      - uses: actions/checkout@v4
      - run: ls -la
      - run: 
          cd javademo/my-app
          mvn install
      - run: java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App
  ciao:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pippo"