name: ciao
run-name: ciao da parte di ${{ github.actor }} 
on: [push]
jobs:
  ciao-fa-cose:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ciaooooooooooooooooooooo"
      - run: 
          cd javademo/my-app
          mvn install
  ciao:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pippo"